export const TRADING_ACCOUNT_REPOSITORY = Symbol(
  "TRADING_ACCOUNT_REPOSITORY",
);
export const PAPER_TRADING_REPOSITORY = Symbol("PAPER_TRADING_REPOSITORY");
export const BROKER_INSTRUMENT_MAPPING_REPOSITORY = Symbol(
  "BROKER_INSTRUMENT_MAPPING_REPOSITORY",
);
