upstream rmsm_web {
    server web:3000;
}

upstream rmsm_api {
    server api:3001;
}

upstream rmsm_admin {
    server admin:3002;
}

upstream rmsm_ai {
    server ai:8000;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 100M;

    location = /health {
        access_log off;
        return 200 "Gateway Healthy\n";
        add_header Content-Type text/plain;
    }

    location /api/ {
        proxy_pass http://rmsm_api;
        include /etc/nginx/snippets/proxy.conf;
    }

    location /admin/ {
        proxy_pass http://rmsm_admin;
        include /etc/nginx/snippets/proxy.conf;
    }

    location /ai/ {
        proxy_pass http://rmsm_ai;
        include /etc/nginx/snippets/proxy.conf;
    }

    location / {
        proxy_pass http://rmsm_web;
        include /etc/nginx/snippets/proxy.conf;
    }
}