import type { DrawingType } from './types';

export const DRAWING_COLORS: Record<DrawingType, string> = {
  SELECT: '#38BDF8',
  TREND_LINE: '#38BDF8',
  HORIZONTAL_LINE: '#38BDF8',
  VERTICAL_LINE: '#38BDF8',
  RAY: '#38BDF8',
  RECTANGLE: '#38BDF8',
  ARROW: '#38BDF8',
  TEXT: '#FFFFFF',

  PARALLEL_CHANNEL: '#A78BFA',
  PRICE_CHANNEL: '#A78BFA',
  REGRESSION_CHANNEL: '#A78BFA',

  FIB_RETRACEMENT: '#FBBF24',
  FIB_EXTENSION: '#FBBF24',
  FIB_PROJECTION: '#FBBF24',
  FIB_TIME: '#FBBF24',

  ABCD: '#22D3EE',
  XABCD: '#22D3EE',
  HEAD_SHOULDERS: '#22D3EE',
  TRIANGLE: '#22D3EE',
  WEDGE: '#22D3EE',

  FORECAST: '#34D399',
  PROJECTION: '#34D399',

  MEASURE_PRICE: '#FB7185',
  MEASURE_TIME: '#FB7185',
  MEASURE_PRICE_TIME: '#FB7185',
  MEASURE_RANGE: '#FB7185',
};
