import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api-client";
import type { Paginated, StrategySummary } from "../types";

export function useStrategySummaries() {
  return useQuery({
    queryKey: ["strategy-summaries"],
    queryFn: () => api.get<Paginated<StrategySummary>>("/strategies?pageSize=500"),
  });
}

/** `GET /strategies/:id` — the Phase 4A domain-layer strategy, a
 * genuinely different aggregate (and id space) from the rule-tree
 * Strategy Builder's own `strategy-engine` strategies. Opportunity's
 * `strategyId` field refers to *this* domain, not the Strategy Builder
 * — linking it to `/strategies/:id` (the Builder's own route) would be
 * wrong and could 404 or show unrelated data. Used only for read-only
 * correlation display (e.g. "generated by strategy X"), never linked
 * into the Builder's own pages. */
export function useStrategySummary(id: string | null) {
  return useQuery({
    queryKey: ["strategy-summaries", id],
    queryFn: () => api.get<StrategySummary>(`/strategies/${id}`),
    enabled: !!id,
  });
}
