"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Search, ArrowUpDown, TrendingUp, TrendingDown, Minus } from "lucide-react";
import {
  Input,
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
  Badge,
  Skeleton,
  Alert,
  AlertDescription,
} from "@rmsm/ui";
import { EmptyState } from "@/components/ui-extra/empty-state";
import { TablePagination } from "@/components/ui-extra/table-pagination";
import { useDebouncedValue } from "@/hooks/use-debounced-value";
import { useOpportunities } from "@/features/opportunities/hooks/use-opportunities";
import { derivePriority, type Priority } from "@/features/opportunities/lib/priority";
import { paginateClientSide } from "@/lib/paginate-client-side";
import type { Opportunity } from "@/features/opportunities/types";

type SortKey = "createdAt" | "confidenceScore" | "priority";
const PRIORITY_RANK: Record<Priority, number> = { HIGH: 2, MEDIUM: 1, LOW: 0 };
const PAGE_SIZE = 20;

function DirectionIcon({ direction }: { direction: Opportunity["signalDirection"] }) {
  return direction === "BUY" ? (
    <span className="flex items-center gap-1 text-success">
      <TrendingUp className="h-3.5 w-3.5" aria-hidden="true" /> Buy
    </span>
  ) : (
    <span className="flex items-center gap-1 text-destructive">
      <TrendingDown className="h-3.5 w-3.5" aria-hidden="true" /> Sell
    </span>
  );
}

function PriorityBadge({ priority }: { priority: Priority }) {
  const variant = priority === "HIGH" ? "success" : priority === "MEDIUM" ? "warning" : "secondary";
  return <Badge variant={variant}>{priority}</Badge>;
}

export default function OpportunityFeedPage() {
  const opportunitiesQuery = useOpportunities();
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState<Opportunity["status"] | "ALL">("ALL");
  const [direction, setDirection] = useState<Opportunity["signalDirection"] | "ALL">("ALL");
  const [strength, setStrength] = useState<Opportunity["signalStrength"] | "ALL">("ALL");
  const [sortKey, setSortKey] = useState<SortKey>("createdAt");
  const [sortDir, setSortDir] = useState<"asc" | "desc">("desc");
  const [page, setPage] = useState(1);
  const debouncedSearch = useDebouncedValue(search, 300);

  const filtered = useMemo(() => {
    const all = opportunitiesQuery.data?.items ?? [];
    const q = debouncedSearch.trim().toUpperCase();
    return all.filter((o) => {
      if (status !== "ALL" && o.status !== status) return false;
      if (direction !== "ALL" && o.signalDirection !== direction) return false;
      if (strength !== "ALL" && o.signalStrength !== strength) return false;
      if (q && !o.symbolCode.toUpperCase().includes(q)) return false;
      return true;
    });
  }, [opportunitiesQuery.data, status, direction, strength, debouncedSearch]);

  const sorted = useMemo(() => {
    const copy = [...filtered];
    const dir = sortDir === "asc" ? 1 : -1;
    copy.sort((a, b) => {
      if (sortKey === "confidenceScore") return (a.confidenceScore - b.confidenceScore) * dir;
      if (sortKey === "priority") return (PRIORITY_RANK[derivePriority(a)] - PRIORITY_RANK[derivePriority(b)]) * dir;
      return (new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()) * dir;
    });
    return copy;
  }, [filtered, sortKey, sortDir]);

  const { pageItems, meta } = paginateClientSide(sorted, page, PAGE_SIZE);

  function toggleSort(key: SortKey) {
    if (sortKey === key) {
      setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    } else {
      setSortKey(key);
      setSortDir("desc");
    }
  }

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-xl font-semibold">Opportunity Feed</h1>
        <p className="text-sm text-muted-foreground">Live trade opportunities generated by your active strategies.</p>
      </div>

      <div className="flex flex-wrap items-center gap-2">
        <div className="relative min-w-[200px] flex-1">
          <Search className="pointer-events-none absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" aria-hidden="true" />
          <Input
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
              setPage(1);
            }}
            placeholder="Search by symbol…"
            className="pl-8"
            aria-label="Search opportunities"
          />
        </div>
        <Select
          value={status}
          onValueChange={(v: Opportunity["status"] | "ALL") => {
            setStatus(v);
            setPage(1);
          }}
        >
          <SelectTrigger className="w-40" aria-label="Filter by status">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="ALL">All statuses</SelectItem>
            <SelectItem value="PENDING">Pending</SelectItem>
            <SelectItem value="CONFIRMED">Confirmed</SelectItem>
            <SelectItem value="EXPIRED">Expired</SelectItem>
            <SelectItem value="REJECTED">Rejected</SelectItem>
          </SelectContent>
        </Select>
        <Select
          value={direction}
          onValueChange={(v: Opportunity["signalDirection"] | "ALL") => {
            setDirection(v);
            setPage(1);
          }}
        >
          <SelectTrigger className="w-36" aria-label="Filter by direction">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="ALL">Any direction</SelectItem>
            <SelectItem value="BUY">Buy</SelectItem>
            <SelectItem value="SELL">Sell</SelectItem>
          </SelectContent>
        </Select>
        <Select
          value={strength}
          onValueChange={(v: Opportunity["signalStrength"] | "ALL") => {
            setStrength(v);
            setPage(1);
          }}
        >
          <SelectTrigger className="w-40" aria-label="Filter by signal strength">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="ALL">Any strength</SelectItem>
            <SelectItem value="STRONG">Strong</SelectItem>
            <SelectItem value="MODERATE">Moderate</SelectItem>
            <SelectItem value="WEAK">Weak</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {opportunitiesQuery.isError && (
        <Alert variant="destructive">
          <AlertDescription>Couldn&apos;t load opportunities. Please try again.</AlertDescription>
        </Alert>
      )}

      {opportunitiesQuery.isLoading ? (
        <div className="space-y-2">
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-10 w-full" />
          ))}
        </div>
      ) : pageItems.length === 0 ? (
        <EmptyState icon={<Minus className="h-8 w-8" />} title="No opportunities match your filters" />
      ) : (
        <div className="overflow-x-auto rounded-md border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>
                  <button type="button" className="flex items-center gap-1 font-medium" onClick={() => toggleSort("priority")}>
                    Priority <ArrowUpDown className="h-3 w-3 text-muted-foreground" aria-hidden="true" />
                  </button>
                </TableHead>
                <TableHead>Symbol</TableHead>
                <TableHead>Direction</TableHead>
                <TableHead>Strength</TableHead>
                <TableHead>
                  <button type="button" className="flex items-center gap-1 font-medium" onClick={() => toggleSort("confidenceScore")}>
                    Confidence <ArrowUpDown className="h-3 w-3 text-muted-foreground" aria-hidden="true" />
                  </button>
                </TableHead>
                <TableHead>Status</TableHead>
                <TableHead>
                  <button type="button" className="flex items-center gap-1 font-medium" onClick={() => toggleSort("createdAt")}>
                    Created <ArrowUpDown className="h-3 w-3 text-muted-foreground" aria-hidden="true" />
                  </button>
                </TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {pageItems.map((o) => (
                <TableRow key={o.id}>
                  <TableCell>
                    <PriorityBadge priority={derivePriority(o)} />
                  </TableCell>
                  <TableCell>
                    <Link href={`/opportunities/${o.id}`} className="font-medium hover:underline">
                      {o.symbolCode}
                    </Link>
                  </TableCell>
                  <TableCell>
                    <DirectionIcon direction={o.signalDirection} />
                  </TableCell>
                  <TableCell>{o.signalStrength}</TableCell>
                  <TableCell className="tabular-nums">{o.confidenceScore.toFixed(0)}%</TableCell>
                  <TableCell>
                    <Badge variant={o.status === "CONFIRMED" ? "success" : o.status === "REJECTED" || o.status === "EXPIRED" ? "destructive" : "warning"}>
                      {o.status}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-sm text-muted-foreground">{new Date(o.createdAt).toLocaleString()}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          <TablePagination pagination={meta} onPageChange={setPage} />
        </div>
      )}
    </div>
  );
}
